### ISSUE TITLE
JS error on Foundry when create a Folder into a compendium. type - Item 

### ISSUE THREAD

**Issue by aesmiol** [earlSt1/vtt-compendium-folders#132]
**Describe the bug**
When I crete a new folder into a compendium of type item , Foundry show a JS error.
This happen only with kind of type

fic-folders.js:1474 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertAdjacentElement')
[Detected 1 package: compendium-folders]
    at Function.createNewFolderButtonWithinCompendium (fic-folders.js:1474:25)
    at fic-folders.js:587:28
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at Compendium._render (foundry.js:3117:13)
    
When move a new items to this compendium , the compendium show #[CF_tempEntity]
When move item into directory , show #[CF_tempEntity]    

**To Reproduce**
Create a new compendium type item and add create a  director into compendium

**Expected behavior**

**Screenshots**
<img width="313" alt="Captura de pantalla 2022-02-08 a las 11 51 12" src="https://user-images.githubusercontent.com/99253540/152973055-4720362f-1b88-40cc-aedc-af9f4c7f0664.png">

<img width="426" alt="Captura de pantalla 2022-02-08 a las 11 51 28" src="https://user-images.githubusercontent.com/99253540/152973084-b934a532-80e4-4c1c-b414-baa370940d91.png">

<img width="277" alt="Captura de pantalla 2022-02-08 a las 11 51 35" src="https://user-images.githubusercontent.com/99253540/152973110-a6a1b95c-bc2f-4e93-bc0d-222c43eee685.png">

Move Item:

<img width="549" alt="Captura de pantalla 2022-02-08 a las 11 54 08" src="https://user-images.githubusercontent.com/99253540/152973319-dacbbc88-057f-460d-bb65-cc87fcdbd08f.png">

<img width="281" alt="Captura de pantalla 2022-02-08 a las 11 54 16" src="https://user-images.githubusercontent.com/99253540/152973341-47ca6847-f82c-4196-9369-52120ceb7844.png">

**Information**
- FoundryVTT Version : 9.249
- Compendium Folders Version: 2.4.2
- Game System + Version :Call of Cthulhu 7ª  Version: 0.7.3
- All other modules disabled? (y/n) Only enable : 
- Babele 2.2.3
- Call of Cthulhu Babele Spanish 0.73.1
- libWrapper 1.12.3.0
- Translations Spanish Core 9.245.1

Best Regards

**Comment by earlSt1** [comment]
Hi, thanks for raising this. I believe its because CoC system compendiums look different to normal ones. A solution for the time being is to close + reopen the compendium and the folders will render correctly. Will work on a fix soon.

**Comment by aesmiol** [comment]
Yes, I close  and open and it shows ok. Great, I'll wait for a solution. Thanks for this module :)
