### ISSUE TITLE
Can't close compendiums

### ISSUE THREAD

**Issue by rodskin** [earlSt1/vtt-compendium-folders#136]
can't close compendiums on FVTT Version 9
(chrome 98.0.4758.102)

```
foundry.js:55612 Uncaught (in promise) TypeError: ui.compendium._toggleOpenState is not a function
[No packages detected]
    at Compendium.close (foundry.js:55612:19)
    at Object.onclick (foundry.js:3294:29)
    at HTMLAnchorElement.<anonymous> (foundry.js:3203:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)
    at HTMLAnchorElement.v.handle (jquery.min.js:2:41048)
```

Seems to come from this mo9dule as I don't have the issue without it

**Comment by rodskin** [comment]
Nevermind, I am stupid and my module was not up to date. My bad :)
