### ISSUE TITLE
Import drag and drop to compendium failing

### ISSUE THREAD

**Issue by Biggoron144** [earlSt1/vtt-compendium-folders#158]
Throwing this error whenever I try to drag an item to an open compendium, this is with only libwrapper and compendium folders activated:

libWrapper-wrapper.js:673 
        
       Uncaught TypeError: TextEditor.getDragEventData is not a function
[Detected 2 packages: compendium-folders, lib-wrapper]
    at 🎁Compendium.prototype._onDrop#compendium-folders (fic-folders.js:645:37)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁Compendium.prototype._onDrop#0 (libWrapper-wrapper.js:189:20)
    at DragDrop.callback (foundry.js:44308:42)
    at DragDrop._handleDrop (foundry.js:44359:17)

**Comment by Biggoron144** [comment]
Seems like this was fixed by updating to the latest v9 stable release, sorry.
