### ISSUE TITLE
Import Compendium to world with merge with name on, fails (v10)

### ISSUE THREAD

**Issue by tratos2** [earlSt1/vtt-compendium-folders#160]
In v10, when importing a folder from a compendium with Merge with name on, it seems the creation of the folder throws the following error:
       Compendium Folders | TypeError: Cannot read properties of null (reading 'name')

When importing the same folder without Merge with name on, the error is not thrown. 

Any solution to this?

**Comment by earlSt1** [comment]
Hi, thanks for raising this, will look into it today

**Comment by earlSt1** [comment]
I just released v2.5.2 which should fix this issue. Will close the issue for now but let me know if it reappears

**Comment by tratos2** [comment]
Yea, no rush. Sorry to add more, but it seems that dragging any new or existing journal entry from the world into a compendium folder doesn't work either.  Might be the same thing

From console when moving to any folder in a compendium:

Compendium Folders | Moving document PHFNdfCTJFY95yfv to new folder
       
       Uncaught (in promise) Error: The key PHFNdfCTJFY95yfv does not exist in the CompendiumCollection Collection
    at CompendiumCollection.get (commons.js:2826:15)
    at CompendiumCollection.get (foundry.js:14443:18)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12552:26)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:12476:22)
    at async Actor5e.updateDocuments (commons.js:5652:23)
    at async FICUtils.packUpdateEntities (fic-folders.js:19:16)
    at async FICFolderAPI.applyUpdates (fic-folders.js:2840:9)
    at async FICFolderAPI.moveDocumentIntoFolder (fic-folders.js:2428:9)

From console when moving to root:

Compendium Folders | Moving document sX2mzfGNJyUx69lf to root
foundry.js:13635 
        
       Uncaught (in promise) Error: Invalid Document type 'undefined' provided to Actor5e.fromDropData.
    at Actor5e.fromDropData (foundry.js:13635:13)
    at async Compendium._onDrop (foundry.js:71123:22)

fromDropData @ foundry.js:13635
await in fromDropData (async)
(anonymous) @ fic-folders.js:935
wrapper @ shim.js:40
callback @ foundry.js:55958
_handleDrop @ foundry.js:56009
        
       Uncaught (in promise) Error: The key sX2mzfGNJyUx69lf does not exist in the CompendiumCollection Collection
    at CompendiumCollection.get (commons.js:2826:15)
    at CompendiumCollection.get (foundry.js:14443:18)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12552:26)
    at async ClientDatabaseBackend._updateDocuments (foundry.js:12476:22)
    at async Actor5e.updateDocuments (commons.js:5652:23)
    at async FICUtils.packUpdateEntities (fic-folders.js:19:16)
    at async FICFolderAPI.applyUpdates (fic-folders.js:2840:9)
    at async FICFolderAPI.moveDocumentToRoot (fic-folders.js:2558:13)
    at async FICUtils.handleMoveToRoot (fic-folders.js:283:13)

**Comment by earlSt1** [comment]
Ooh interesting, I'll break this out into a new issue and look into it later
